[package]
name = "termcube"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.16"
winit = "0.28"
bytemuck = { version = "1.18.0", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
